/*
 *
 * PRESLPC-specific JS functions...
 * If you want to make your own customizations for your institution, use the custom.js 
 * file provided in the same directory.
 * If you found out a bug in this PRESPCL script, please contact the author ASAP so they 
 * can make a patch for everyone.
 *
 * author: Mathilde Guerin (mathilde.guerin@univ-lr.fr)
 * 
 */
 
/*
 * ====================================
 *  DO NOT EDIT THIS FILE
 * ====================================
 */


(function($){
	$(document).ready(function(){
		/* Adds a control in the "portlet title bar" when it is an iframe to open the framed service in new window */
		$('iframe').each(function(){		
			var portletContent = $(this).parents().filter('div[id*=portletContent_]');
			var chanId = $(portletContent).attr('id').split('_')[1]
			var controls = $('#toolbar_'+chanId+' .up-portlet-controls');
			
			$('<a href="'+this.src+'" target="_blank" title="Ouvrir dans une nouvelle fenetre" id="openIframe_'+chanId+'" '
				+ 'class="up-portlet-control openIframe"><span class=icon></span><span class="label">Ouvrir</span></a>').appendTo($(controls));				
		});
	});
})(jQuery);